// Generated by ChatGPT
// This file contains functions for setting, getting, and deleting cookies.
// These are client-side only, used for things like showing toast after forking.
export function setCookie(
  name: string,
  value: string,
  days?: number,
): void {
  // Do nothing if we're in the server
  if (typeof window === 'undefined') return;

  let expires = '';
  if (days) {
    const date = new Date();
    date.setTime(
      date.getTime() + days * 24 * 60 * 60 * 1000,
    );
    expires = '; expires=' + date.toUTCString();
  }
  document.cookie =
    name + '=' + (value || '') + expires + '; path=/';
}

export function getCookie(name: string): string | null {
  // Return null if we're in the server
  if (typeof window === 'undefined') return null;

  const nameEQ = name + '=';
  const ca = document.cookie.split(';');
  for (let i = 0; i < ca.length; i++) {
    let c = ca[i];
    while (c.charAt(0) == ' ') c = c.substring(1, c.length);
    if (c.indexOf(nameEQ) == 0)
      return c.substring(nameEQ.length, c.length);
  }
  return null;
}

export function deleteCookie(name: string): void {
  // Do nothing if we're in the server
  if (typeof window === 'undefined') return;

  document.cookie =
    name +
    '=; expires=Thu, 01 Jan 1970 00:00:01 GMT; path=/';
}
