import { getAuthenticatedUser } from '../getAuthenticatedUser';
import { PricingPage, PricingPageData } from './index';

PricingPage.getPageData = async ({
  gateways,
  auth0User,
}): Promise<PricingPageData> => {
  const { authenticatedUserSnapshot } =
    await getAuthenticatedUser({
      gateways,
      auth0User,
    });

  const pageData: PricingPageData = {
    title: 'VizHub Pricing',
    authenticatedUserSnapshot,
    description: [
      // Inspired by result generated by Google's AI 6/7/2023
      'VizHub Pricing Page, with options to upgrade to the Pro plan',
      'which includes additional features such as private vizzes.',
    ].join(' '),
    image:
      'https://vizhub.com/api/visualization/preview/77a2f42571494263931b8c4d38b7d63c.png',
  };

  return pageData;
};

export { PricingPage };
