services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "0.0.0.0:27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb

volumes:
  mongodb_data:
  mongodb_config:
