import { CommitId, VizId } from 'entities';

// A VizHub-specific error code.
export enum VizHubErrorCode {
  // When a resource is not found.
  // e.g. an invalid id was used, or a viz was deleted
  resourceNotFound = 'resourceNotFound',
  invalidCommitOp = 'invalidCommitOp',
  invalidDecrement = 'invalidDecrement',
  missingParameter = 'missingParameter',
}

// Errors generated by gateway methods be of this type.
export class VizHubError extends Error {
  code: VizHubErrorCode;
  constructor(message: string, code: VizHubErrorCode) {
    super(message);
    this.name = 'VizHubError';
    this.code = code;
  }
}

export const resourceNotFoundError = (id: string): VizHubError =>
  new VizHubError(
    'Resource not found with id: ' + id,
    VizHubErrorCode.resourceNotFound
  );

export const invalidCommitOp = (
  commitId: CommitId,
  message: string
): VizHubError =>
  new VizHubError(
    'Invalid op in commit with id: ' + commitId + '\n' + message,
    VizHubErrorCode.invalidCommitOp
  );

export const invalidDecrementError = (id: VizId, field: string): VizHubError =>
  new VizHubError(
    'Cannot decrement zero-value field `' + field + '` on viz `' + id + '`',
    VizHubErrorCode.invalidCommitOp
  );

export const missingParameterError = (parameter: string): VizHubError =>
  new VizHubError(
    'Missing parameter: ' + parameter,
    VizHubErrorCode.missingParameter
  );
